services:
  comicinfo-generator:
    image: ghcr.io/jakej985-rgb/comicinfo-generator:v0.5
    build:
      context: .
      dockerfile: Dockerfile
    container_name: comicinfo-generator
    restart: unless-stopped
    ports:
      - "5005:5005"
    environment:
      - COMICINFO_HOST=0.0.0.0
      - COMICINFO_PORT=5005
      - COMICINFO_CONFIG=/config/config.yaml
      - COMICINFO_LIBRARY_ROOTS=/comics
    volumes:
      - ./config:/config
      - /mnt/disk1/Comics:/comics
